# Regenerates the dashboard's build thumbnails. LOCAL FALLBACK ONLY.
#
# The primary path is the Thumbnails workflow in .github/workflows, which discovers builds
# from GitHub, renders them on a runner, and commits the result — so a build published by
# someone without write access here still gets a picture. Reach for this script only when
# you need to re-render on this machine, e.g. to check a capture before CI does.
#
# Note that thumbs/builds.txt is now GENERATED by tools/render-thumbnails.mjs. Editing it
# to add a build does nothing; the workflow will overwrite it on the next run.
#
# Why this exists: the dashboard runs as a claude.ai Artifact under a CSP that blocks
# every external host. A remote <img> cannot load and neither can an <iframe> of the
# build, so a thumbnail has to already be inside the page as a data URI. This script
# renders each build's live GitHub Pages URL with headless Chrome, shrinks it to a
# 640x400 JPEG, and injects the whole set into yf-builds-dashboard.artifact.html.
#
# Run it after publishing a new build, or when a build changes visibly:
#   powershell -File tools/refresh-thumbnails.ps1
#
# Then republish the artifact from Claude Code so the team sees the new tiles.

param(
  [string]$Html = "yf-builds-dashboard.artifact.html",
  [string]$ShotDir = "thumbs",
  # Render only these slugs. Injection still covers every slug that has a jpg on disk,
  # so a subset run tops one build up without disturbing the rest.
  [string[]]$Only = @()
)

$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Drawing

$chrome = @(
  "C:\Program Files\Google\Chrome\Application\chrome.exe",
  "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
  "C:\Program Files\Microsoft\Edge\Application\msedge.exe"
) | Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $chrome) { throw "No Chromium browser found - install Chrome or Edge." }

# Every build with a live URL. Keep this list in step with the registry's Live URL column.
# The slug list is DATA, in thumbs/builds.txt, not an array in this script.
#
# It used to be hardcoded here, which meant a newly published build got no thumbnail
# until somebody remembered to come and edit a PowerShell script. That is exactly how
# YF Operating Model Visualization shipped on 2026-08-21 with a hazard tile: the repo
# existed, Pages served it, the registry row was correct, and the renderer had simply
# never been told the slug. Appending a line to a text file is a step a builder can be
# asked to do; editing a script is not.
# $ShotDir is still the relative default ("thumbs") at this point - it is resolved to an
# absolute path further down - so join against it as-is rather than deriving a parent.
$listFile = Join-Path $ShotDir "builds.txt"
if (-not (Test-Path $listFile)) { throw "No slug list found at $listFile - nothing to render." }

$builds = Get-Content $listFile |
  ForEach-Object { $_.Trim() } |
  Where-Object { $_ -and -not $_.StartsWith("#") }

if (-not $builds) { throw "$listFile contains no slugs." }
"reading slugs from : $listFile ($($builds.Count) builds)"

New-Item -ItemType Directory -Force $ShotDir | Out-Null
# Chrome resolves --screenshot against its OWN working directory, not this script's, so a
# relative path here fails with "cannot find the path specified". Absolute from here on.
$ShotDir = (Resolve-Path $ShotDir).Path

$jpegEncoder = [System.Drawing.Imaging.ImageCodecInfo]::GetImageEncoders() |
  Where-Object { $_.MimeType -eq "image/jpeg" }
$encParams = New-Object System.Drawing.Imaging.EncoderParameters 1
$encParams.Param[0] = New-Object System.Drawing.Imaging.EncoderParameter(
  [System.Drawing.Imaging.Encoder]::Quality, 62)

$renderList = if ($Only.Count) { $builds | Where-Object { $Only -contains $_ } } else { $builds }
if ($Only.Count) { "rendering subset    : $($renderList -join ', ')" }

foreach ($name in $renderList) {
  $url = "https://yfagency.github.io/$name/"
  # The PNG is a throwaway intermediate, so it goes to temp rather than the repo. This
  # folder lives inside OneDrive, which re-materialises files from its cloud copy shortly
  # after they are deleted — so an intermediate written here comes back and lands in the
  # next commit no matter how carefully the script cleans up after itself.
  $png = Join-Path ([IO.Path]::GetTempPath()) "yfshot-$name.png"
  $jpg = Join-Path $ShotDir "$name.jpg"

  # virtual-time-budget lets animation and WebGL settle before the frame is taken;
  # enable-unsafe-swiftshader gives headless a software GL implementation, without
  # which the canvas-heavy builds capture black.
  # Chrome reports success on stderr ("N bytes written to file ..."). Windows PowerShell
  # turns any native stderr line into an ErrorRecord, which under ErrorActionPreference
  # = Stop aborts the script on a screenshot that actually worked. Relax it for the call
  # and judge the outcome by whether the file exists.
  # Each render gets its own throwaway profile. Without this, the second and later
  # invocations attach to the still-shutting-down first Chrome, hold no profile lock of
  # their own, and exit silently without writing a file — so only the first build gets a
  # thumbnail and the rest are quietly skipped.
  $profileDir = Join-Path ([IO.Path]::GetTempPath()) ("yfshot-" + [Guid]::NewGuid().ToString("N"))

  $prevEAP = $ErrorActionPreference
  $ErrorActionPreference = "Continue"
  & $chrome --headless=new --disable-gpu --enable-unsafe-swiftshader --hide-scrollbars `
            --no-first-run --no-default-browser-check "--user-data-dir=$profileDir" `
            --window-size=1280,800 --virtual-time-budget=9000 `
            --screenshot="$png" $url *> $null
  $ErrorActionPreference = $prevEAP
  Remove-Item $profileDir -Recurse -Force -ErrorAction SilentlyContinue
  if (-not (Test-Path $png)) { Write-Warning "$name did not render - skipped"; continue }

  $src = [System.Drawing.Image]::FromFile($png)
  $bmp = New-Object System.Drawing.Bitmap 640, 400
  $g = [System.Drawing.Graphics]::FromImage($bmp)
  $g.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
  $g.DrawImage($src, 0, 0, 640, 400)
  $bmp.Save($jpg, $jpegEncoder, $encParams)
  $g.Dispose(); $bmp.Dispose(); $src.Dispose()
  Remove-Item $png

  "{0,-32} {1,7:N0} bytes" -f $name, (Get-Item $jpg).Length

  # Breathe between launches. A throwaway profile per render is not enough on its own:
  # a full 14-build run had six consecutive captures fail while the same six succeeded
  # immediately when run one at a time. Chrome instances tearing down still interfere
  # with the next one starting up.
  Start-Sleep -Milliseconds 1200
}

# Inject from DISK, not from what rendered this run.
#
# This block used to be built inside the render loop, so a run where some captures
# failed replaced the whole THUMBS map with only the successes - silently deleting
# working thumbnails for every build that happened to time out. That is exactly what
# happened on 2026-08-21: six of fourteen renders failed and five good images were
# wiped out of the page. A failed render must cost you a stale image, never a lost one.
$entries = New-Object System.Collections.Generic.List[string]
$missing = New-Object System.Collections.Generic.List[string]
foreach ($name in $builds) {
  $jpg = Join-Path $ShotDir "$name.jpg"
  if (-not (Test-Path $jpg)) { $missing.Add($name); continue }
  $b64 = [Convert]::ToBase64String([IO.File]::ReadAllBytes($jpg))
  $entries.Add('"https://yfagency.github.io/' + $name + '/":"data:image/jpeg;base64,' + $b64 + '"')
}

if ($entries.Count -eq 0) { throw "No thumbnails on disk - aborting without touching $Html" }
if ($missing.Count) {
  Write-Warning ("no image on disk for: " + ($missing -join ", ") +
    " - these will show the hazard tile until a render succeeds")
}

# Replace the whole THUMBS assignment, whatever it currently holds.
#
# Read and write UTF-8 EXPLICITLY. Get-Content -Raw in Windows PowerShell 5.1 decodes
# using the system ANSI codepage, and WriteAllText then re-encodes as UTF-8 — so every
# non-ASCII character in the file gains a layer of mojibake on each run. That silently
# corrupted the dashboard's error messages once already: em dashes and arrows in strings
# the team actually reads. Do not replace these two lines with Get-Content/Out-File.
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
$content = $utf8NoBom.GetString([IO.File]::ReadAllBytes((Resolve-Path $Html)))
$pattern = '(?s)var THUMBS = \{.*?\};'
if ($content -notmatch $pattern) { throw "Could not find the THUMBS block in $Html" }
$js = "var THUMBS = {" + ($entries -join ",`n") + "};"
$content = [regex]::Replace($content, $pattern, { $js }, 1)
[IO.File]::WriteAllText((Resolve-Path $Html), $content, $utf8NoBom)

"injected $($entries.Count) thumbnails into $Html"
